// Generated by CoffeeScript 1.4.0
(function() {
  var Clip, ImageClip,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Clip = (function() {

    function Clip(item) {
      this.item = item;
    }

    return Clip;

  })();

  ImageClip = (function(_super) {

    __extends(ImageClip, _super);

    function ImageClip() {
      ImageClip.__super__.constructor.call(this, {
        "Parrot": "Parrot"
      });
    }

    return ImageClip;

  })(Clip);

}).call(this);
